#!/bin/bash
# QuizCloud Microservices Startup Script
# This script demonstrates the order to start all services

echo "=========================================="
echo "QuizCloud Microservices Startup Guide"
echo "=========================================="
echo ""

echo "PREREQUISITES:"
echo "1. RabbitMQ must be running on localhost:5672"
echo "2. PostgreSQL must be running on localhost:5432"
echo "3. Java 17 must be installed"
echo "4. Each service needs a separate terminal window"
echo ""

echo "STARTUP SEQUENCE:"
echo ""

echo "Step 1: Start Config Server (Port: 8888)"
echo "Command: cd config-server && ./mvnw spring-boot:run"
echo "Wait for: 'Started ConfigServerApplication'"
echo ""

echo "Step 2: Start Service Registry/Eureka (Port: 8761)"
echo "Command: cd service-registry && ./mvnw spring-boot:run"
echo "Wait for: 'Started ServiceRegistryApplication'"
echo "Dashboard: http://localhost:8761"
echo ""

echo "Step 3: Start Zipkin Server (Port: 9411)"
echo "Command: cd zipkin-server && ./mvnw spring-boot:run"
echo "Wait for: 'Started ZipkinServerApplication'"
echo "Dashboard: http://localhost:9411/zipkin/"
echo ""

echo "Step 4: Start API Gateway (Port: 8080)"
echo "Command: cd api-gateway && ./mvnw spring-boot:run"
echo "Wait for: 'Netty started with reactor.netty.http.server.HttpServer'"
echo ""

echo "Step 5: Start Question Service (Port: 8081)"
echo "Command: cd question-service && ./mvnw spring-boot:run"
echo "Wait for: 'Started QuestionServiceApplication'"
echo ""

echo "Step 6: Start Quiz Service (Port: 8082)"
echo "Command: cd quiz-service && ./mvnw spring-boot:run"
echo "Wait for: 'Started QuizServiceApplication'"
echo ""

echo "=========================================="
echo "VERIFICATION"
echo "=========================================="
echo ""
echo "After all services are running, verify:"
echo ""
echo "1. Config Server Health:"
echo "   curl http://localhost:8888/actuator/health"
echo ""
echo "2. Eureka Dashboard:"
echo "   http://localhost:8761/"
echo ""
echo "3. Service Endpoints:"
echo "   - API Gateway: http://localhost:8080/actuator/health"
echo "   - Question Service: http://localhost:8081/actuator/health"
echo "   - Quiz Service: http://localhost:8082/actuator/health"
echo ""
echo "4. Zipkin Tracing:"
echo "   http://localhost:9411/zipkin/"
echo ""
echo "5. Make an API Request (generates trace):"
echo "   curl http://localhost:8080/actuator/health"
echo ""
echo "Then view trace in Zipkin UI"
echo ""

echo "=========================================="
echo "USEFUL COMMANDS"
echo "=========================================="
echo ""
echo "View all microservices registered in Eureka:"
echo "  curl http://localhost:8761/eureka/apps"
echo ""
echo "Get API Gateway configuration:"
echo "  curl http://localhost:8888/api-gateway/default"
echo ""
echo "Get all actuator endpoints:"
echo "  curl http://localhost:8080/actuator"
echo ""
echo "View metrics:"
echo "  curl http://localhost:8080/actuator/metrics"
echo ""
echo "View environment properties:"
echo "  curl http://localhost:8080/actuator/env"
echo ""
