spring.application.name=demoproject
spring.datasource.url=jdbc:mysql://localhost:3306/course_management?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.output.ansi.enabled=ALWAYS
spring.cache.type=simple

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Secret@12345_azxhteubldjbvhekfjdfn
jwt.expiration=300000
LOG_DIR=logs

resilience4j.ratelimiter.instances.globalLimiter.limitForPeriod=20
resilience4j.ratelimiter.instances.globalLimiter.limitRefreshPeriod=20s
resilience4j.ratelimiter.instances.globalLimiter.timeoutDuration=0

resilience4j.ratelimiter.instances.loginLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.loginLimiter.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.loginLimiter.timeoutDuration=0