global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'question-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'quiz-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'service-registry'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8761']
